# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2020, Intel Corporation

#
# src/test/pmem2_usc/Makefile -- build pmem2_usc test
#
TOP = ../../..

vpath %.c $(TOP)/src/test/unittest

TARGET = pmem2_usc
OBJS = pmem2_usc.o\
	ut_pmem2_utils.o

LIBPMEM2=y

include ../Makefile.inc
